--
-- PostgreSQL database dump
--

-- Dumped from database version 12.0 (Debian 12.0-2.pgdg100+1)
-- Dumped by pg_dump version 12.0 (Debian 12.0-2.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bestandene_module; Type: TABLE; Schema: public; Owner: trapper
--

CREATE TABLE public.bestandene_module (
    id bigint NOT NULL,
    modul character varying(255),
    note double precision NOT NULL
);


ALTER TABLE public.bestandene_module OWNER TO trapper;

--
-- Name: bestandene_module_id_seq; Type: SEQUENCE; Schema: public; Owner: trapper
--

ALTER TABLE public.bestandene_module ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bestandene_module_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bewerber; Type: TABLE; Schema: public; Owner: trapper
--

CREATE TABLE public.bewerber (
    kennung character varying(255) NOT NULL,
    geburtsdatum character varying(255),
    nachname character varying(255),
    vorname character varying(255)
);


ALTER TABLE public.bewerber OWNER TO trapper;

--
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: trapper
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO trapper;

--
-- Name: karriere; Type: TABLE; Schema: public; Owner: trapper
--

CREATE TABLE public.karriere (
    id bigint NOT NULL,
    arbeitserfahrung character varying(255),
    abschluss character varying(255),
    studiengang character varying(255),
    fachrichtung character varying(255),
    status boolean NOT NULL
);


ALTER TABLE public.karriere OWNER TO trapper;

--
-- Name: karriere_id_seq; Type: SEQUENCE; Schema: public; Owner: trapper
--

ALTER TABLE public.karriere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.karriere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modul_auswahl; Type: TABLE; Schema: public; Owner: trapper
--

CREATE TABLE public.modul_auswahl (
    id bigint NOT NULL,
    modul character varying(255),
    prioritaet integer NOT NULL,
    praeferenzen_max_wunsch_stunden integer
);


ALTER TABLE public.modul_auswahl OWNER TO trapper;

--
-- Name: modul_auswahl_id_seq; Type: SEQUENCE; Schema: public; Owner: trapper
--

ALTER TABLE public.modul_auswahl ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modul_auswahl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personalien; Type: TABLE; Schema: public; Owner: trapper
--

CREATE TABLE public.personalien (
    id bigint NOT NULL,
    plz character varying(255),
    hausnummer character varying(255),
    "straße" character varying(255),
    wohnort character varying(255),
    wohnstadt character varying(255),
    alter integer NOT NULL,
    geburtsdatum date,
    geburtsort character varying(255),
    name character varying(255),
    nationalitaet character varying(255),
    unikennung character varying(255),
    vorname character varying(255)
);


ALTER TABLE public.personalien OWNER TO trapper;

--
-- Name: praeferenzen; Type: TABLE; Schema: public; Owner: trapper
--

CREATE TABLE public.praeferenzen (
    max_wunsch_stunden integer NOT NULL,
    einstiegs_typ character varying(255),
    modul character varying(255),
    einschraenkungen character varying(255),
    einstieg_typ character varying(255),
    kommentar character varying(255),
    min_wunsch_stunden integer NOT NULL,
    tutoren_schulung_teilnahme character varying(255)
);


ALTER TABLE public.praeferenzen OWNER TO trapper;

--
-- Name: praeferenzen_max_wunsch_stunden_seq; Type: SEQUENCE; Schema: public; Owner: trapper
--

ALTER TABLE public.praeferenzen ALTER COLUMN max_wunsch_stunden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.praeferenzen_max_wunsch_stunden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bestandene_module; Type: TABLE DATA; Schema: public; Owner: trapper
--

COPY public.bestandene_module (id, modul, note) FROM stdin;
\.


--
-- Data for Name: bewerber; Type: TABLE DATA; Schema: public; Owner: trapper
--

COPY public.bewerber (kennung, geburtsdatum, nachname, vorname) FROM stdin;
\.


--
-- Data for Name: karriere; Type: TABLE DATA; Schema: public; Owner: trapper
--

COPY public.karriere (id, arbeitserfahrung, abschluss, studiengang, fachrichtung, status) FROM stdin;
\.


--
-- Data for Name: modul_auswahl; Type: TABLE DATA; Schema: public; Owner: trapper
--

COPY public.modul_auswahl (id, modul, prioritaet, praeferenzen_max_wunsch_stunden) FROM stdin;
\.


--
-- Data for Name: personalien; Type: TABLE DATA; Schema: public; Owner: trapper
--

COPY public.personalien (id, plz, hausnummer, "straße", wohnort, wohnstadt, alter, geburtsdatum, geburtsort, name, nationalitaet, unikennung, vorname) FROM stdin;
\.


--
-- Data for Name: praeferenzen; Type: TABLE DATA; Schema: public; Owner: trapper
--

COPY public.praeferenzen (max_wunsch_stunden, einstiegs_typ, modul, einschraenkungen, einstieg_typ, kommentar, min_wunsch_stunden, tutoren_schulung_teilnahme) FROM stdin;
\.


--
-- Name: bestandene_module_id_seq; Type: SEQUENCE SET; Schema: public; Owner: trapper
--

SELECT pg_catalog.setval('public.bestandene_module_id_seq', 1, false);


--
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: trapper
--

SELECT pg_catalog.setval('public.hibernate_sequence', 1, false);


--
-- Name: karriere_id_seq; Type: SEQUENCE SET; Schema: public; Owner: trapper
--

SELECT pg_catalog.setval('public.karriere_id_seq', 1, false);


--
-- Name: modul_auswahl_id_seq; Type: SEQUENCE SET; Schema: public; Owner: trapper
--

SELECT pg_catalog.setval('public.modul_auswahl_id_seq', 1, false);


--
-- Name: praeferenzen_max_wunsch_stunden_seq; Type: SEQUENCE SET; Schema: public; Owner: trapper
--

SELECT pg_catalog.setval('public.praeferenzen_max_wunsch_stunden_seq', 1, false);


--
-- Name: bestandene_module bestandene_module_pkey; Type: CONSTRAINT; Schema: public; Owner: trapper
--

ALTER TABLE ONLY public.bestandene_module
    ADD CONSTRAINT bestandene_module_pkey PRIMARY KEY (id);


--
-- Name: bewerber bewerber_pkey; Type: CONSTRAINT; Schema: public; Owner: trapper
--

ALTER TABLE ONLY public.bewerber
    ADD CONSTRAINT bewerber_pkey PRIMARY KEY (kennung);


--
-- Name: karriere karriere_pkey; Type: CONSTRAINT; Schema: public; Owner: trapper
--

ALTER TABLE ONLY public.karriere
    ADD CONSTRAINT karriere_pkey PRIMARY KEY (id);


--
-- Name: modul_auswahl modul_auswahl_pkey; Type: CONSTRAINT; Schema: public; Owner: trapper
--

ALTER TABLE ONLY public.modul_auswahl
    ADD CONSTRAINT modul_auswahl_pkey PRIMARY KEY (id);


--
-- Name: personalien personalien_pkey; Type: CONSTRAINT; Schema: public; Owner: trapper
--

ALTER TABLE ONLY public.personalien
    ADD CONSTRAINT personalien_pkey PRIMARY KEY (id);


--
-- Name: praeferenzen praeferenzen_pkey; Type: CONSTRAINT; Schema: public; Owner: trapper
--

ALTER TABLE ONLY public.praeferenzen
    ADD CONSTRAINT praeferenzen_pkey PRIMARY KEY (max_wunsch_stunden);


--
-- Name: modul_auswahl fk4ewboi7f0i8bghmwn4waiojs9; Type: FK CONSTRAINT; Schema: public; Owner: trapper
--

ALTER TABLE ONLY public.modul_auswahl
    ADD CONSTRAINT fk4ewboi7f0i8bghmwn4waiojs9 FOREIGN KEY (praeferenzen_max_wunsch_stunden) REFERENCES public.praeferenzen(max_wunsch_stunden);


--
-- PostgreSQL database dump complete
--

