= Softwareentwicklung im Team: Vorbereitung auf das Projekt
WS19/20
:icons: font
:icon-set: octicon
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Gruppenbildung

Für das Abschlussprojekt bilden Sie bitte eine Gruppe im GitHub Classroom, die
aus 7 bis 9 Personen besteht und laden eine entsprechende `gruppe.yml` in AUAS
hoch. Im Gegensatz zu den normalen Blättern haben Sie volle
Administrationsrechte und alle Projekte sind öffentlich um den Austausch mit
anderen Gruppen bei Integrationen zwischen Anwendungen einfacher zu gestalten.

IMPORTANT: Bitte entfernen Sie nicht die Organisatoren aus Ihrem Projekt.

NOTE: Sie finden neben dieser README eine
link:gruppe.yml[Beispiel-Gruppe-YML-Datei]. Füllen Sie diese aus, checken Sie
sie ein.

IMPORTANT: Erstellen Sie direkt eine Abgabe in AUAS. Diese ist *essentiell* für
die Teilnahme am Praktikum. Diesmal muss die Abgabe eine ZIP-Datei sein. Die
ZIP-Datei soll die `gruppe.yml` und eine _optionale_ Beschreibung eines eigenen
Systems für MOPS beinhalten. Sie können natürlich auch einfach die
vorgeschlagenen Systeme wählen und müssen keine eigenen Systeme entwerfen.

== Systeme

*Die folgenden Beschreibungen sind keine Spezifikationen, die den Funktionsumfang der Projekte festlegen,* sondern nur ein "Braindump" von den Ideen, die mir zu dem entsprechenden System gekommen sind. Die Beschreibungen sollen Ihnen primär helfen, Systeme auszusuchen, die Sie umsetzen möchten. Wenn Sie einen eigenen Vorschlag für ein System haben, können Sie das auch gerne vorschlagen. Sie müssen dann zusammen mit der `gruppe.yml` Datei einen kurzen Pitch (in etwa wie in diesem Dokument) einreichen, damit wir uns vorstellen können, was Sie machen wollen und den Umfang begutachten.

=== Korrektorinnen Bewerbung
In jedem Semester werden studentische Hilfskräfte für den Übungsbetrieb benötigt. In (zumindest) den Grundlagenveranstaltungen wird dazu ein gemeinsames Bewerbungsverfahren benutzt:

* Bewerber füllen einen Fragebogen aus.
* Nach Ablauf der Frist werden die Bewerberinnen, die potentiell für eine Stelle in Frage kommen gruppiert und den Verantwortlichen der Veranstaltung zur Verfügung gestellt. Bewerberinnen kommen in Frage, wenn sie eine Veranstaltung nicht ausgeschlossen haben.
* Die Verantwortlichen geben für jede Bewerbung eine Priorität an.
* Die Verteilung auf die einzelnen Veranstaltungen werden von einer verantwortlichen Person manuell durchgeführt, dazu wird aber eine hinreichend gute Darstellung der gesammelten Informationen gebraucht
* Am Ende sollen automatisch die Einstellungsbögen für die Personalabteilung als PDF erzeugt werden
