name: Deploy Application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install node modules
        run: npm install
      - name: Run gulp
        run: gulp
      - name: Check Java Files
        run: gradle check
      - name: Build jar file
        run: gradle dist