name: Docker-Compose & Gradle checks

on: pull_request

jobs:
  gradleCheck:
    needs: db
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
        
    - name: Build and start Docker container
      run: docker-compose up -d
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean build folder
      run: ./gradlew clean
      
    - name: Build with Gradle
      run: ./gradlew check
